import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { FloatingAdminButton } from "@repo/ui/floating-admin-button";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
    <head> 
      <link
          href="https://fonts.googleapis.com/icon?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
    </head>

      <body className={geist.className}>
        <main className="flex-1 flex flex-col justify-center px-4 min-h-screen bg-gradient-to-b from-black via-gray-900 via-70% to-gray-800 relative">
            {children}
        </main>
        <div id="modal-root" />
        <FloatingAdminButton />
      </body>
    </html>
  );
}
